version: "1.0"

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
  backend:
    build: backend
    depends_on:
      - "database"
    ports:
      - "5454:5454"

  frontend:
    build: frontend
    depends_on:
      - "backend"
    ports:
      - "8080:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
