# https://taskfile.dev

version: "3"

tasks:
  setup:
    cmds:
      - go mod download
      - go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
      - go install github.com/fatih/gomodifytags@latest
      - mkdir -p autogen
  regen:
    cmds:
      - oapi-codegen -generate="types,server,strict-server,spec" -package autogen spec.yml > autogen/inte.gen.go
      - go mod tidy
      - gomodifytags -all -file ./autogen/inte.gen.go -add-tags bson -w > /dev/null
